LOCAL_SRC_FILES=\
 Test.cpp\
 EventListener.cpp\
 UpdateThread.cpp\
 Thread.cpp\
 InspiryLog.cpp\
 Mutex.cpp\
 UartCmd.cpp\
 Condition.cpp\
 Uart.cpp\
 SerialDevice.cpp\
 Com.cpp\
 inspiry_log.cpp\
	
all:
	g++ -D_LINUX_UBUNTU_  -g $(LOCAL_SRC_FILES)  -o update -lpthread
clean:
	rm update
